apiVersion: v1
data:
  host: db
  port: "8080"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-21T08:49:30Z"
  name: db-config
  namespace: demo
  resourceVersion: "1473"
  selfLink: /api/v1/namespaces/demo/configmaps/db-config
  uid: 64e740ac-abb3-42e6-a98e-9e1585f3b57f
